/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reciepe.manager.application;
import model.user;
import dao.Userdao;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author anusr
 */
public class login extends javax.swing.JFrame {
public String emailpattern="^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        logbtn.setEnabled(false);
    }
public void clear()
{
    usrt.setText("");
    pwd1.setText("");
    logbtn.setEnabled(false);
    
}
public void validateField()
{
    String name= usrt.getText();
    String password = pwd1.getText();
    if(!password.equals(""))
    {
        logbtn.setEnabled(true);
    }
    else
    {
     logbtn.setEnabled(false);   
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usr = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pwd1 = new javax.swing.JPasswordField();
        usrt = new javax.swing.JTextField();
        logbtn = new javax.swing.JButton();
        fpbtn = new javax.swing.JButton();
        sibtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usr.setText("Username");
        usr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 67, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 116, 74, 24));

        pwd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd1ActionPerformed(evt);
            }
        });
        pwd1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwd1KeyReleased(evt);
            }
        });
        getContentPane().add(pwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 117, 175, 24));
        pwd1.getAccessibleContext().setAccessibleName("pwdl");

        usrt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usrtKeyReleased(evt);
            }
        });
        getContentPane().add(usrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 68, 175, 30));

        logbtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        logbtn.setText("Login");
        logbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 177, 91, -1));

        fpbtn.setText("forgot password?");
        fpbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpbtnActionPerformed(evt);
            }
        });
        getContentPane().add(fpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 217, 127, -1));

        sibtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        sibtn.setText("Signup");
        sibtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        sibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sibtnActionPerformed(evt);
            }
        });
        getContentPane().add(sibtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 180, 74, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 60, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pwd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwd1ActionPerformed

    private void logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbtnActionPerformed
        // TODO add your handling code here:
        String name=usrt.getText();
        String password= pwd1.getText();
        user User=null;
        User =Userdao.login(name,password);
        if(User==null)
        {
            JOptionPane.showMessageDialog(null,"<html><b style=\"color:red\">Incorrect Username or Password</b></html>","Message",JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(User.getStatus().equals("false"))
            {
                ImageIcon icon= new ImageIcon("src/popup/Wait.png");
                JOptionPane.showMessageDialog(null,"<html><b>Wait for admin approval</b></html>","Message",JOptionPane.INFORMATION_MESSAGE,icon);
                clear();
            }
            if(User.getStatus().equals("true"))
            {
                setVisible(false);
                new home(name).setVisible(true);
            }
        }
    }//GEN-LAST:event_logbtnActionPerformed

    private void usrtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usrtKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_usrtKeyReleased

    private void pwd1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwd1KeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_pwd1KeyReleased

    private void sibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sibtnActionPerformed
setVisible(false);
new Signin().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_sibtnActionPerformed

    private void fpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpbtnActionPerformed
new forgotpassword().setVisible(true);        // TODO add your handling code         // TODO add your handling code here:
    }//GEN-LAST:event_fpbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fpbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logbtn;
    private javax.swing.JPasswordField pwd1;
    private javax.swing.JButton sibtn;
    private javax.swing.JLabel usr;
    private javax.swing.JTextField usrt;
    // End of variables declaration//GEN-END:variables
}
