/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reciepe.manager.application;
import model.Category;
import model.Recipe;
import java.util.ArrayList;
import dao.Categorydao;
import java.util.Iterator;
import dao.Recipedao;
/**
 *
 * @author anusr
 */
public class Newrecip extends javax.swing.JFrame {

    /**
     * Creates new form Newrecip
     */
    public Newrecip() {
        initComponents();
        addbtn.setEnabled(false);
    }
public void validateFields()
{
    String rid= txtid.getText();
    String tit=txttil.getText();
    if(!rid.equals("")&& !tit.equals(""))
    {
        addbtn.setEnabled(true);
    }
    else
    {
      addbtn.setEnabled(false);  
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttil = new javax.swing.JTextField();
        txtpt = new javax.swing.JTextField();
        cat = new javax.swing.JComboBox<>();
        txtct = new javax.swing.JTextField();
        txtdis = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        gbbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Enetr the Details of your Recipe");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 393, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 101, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 101, 31));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Category");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 114, 31));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Preparation time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Coocking time");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 101, 28));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Discription");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 101, 33));

        txttil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttilActionPerformed(evt);
            }
        });
        txttil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttilKeyReleased(evt);
            }
        });
        getContentPane().add(txttil, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 158, -1));
        getContentPane().add(txtpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 158, -1));

        getContentPane().add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 158, -1));
        getContentPane().add(txtct, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 158, -1));

        txtdis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdisActionPerformed(evt);
            }
        });
        getContentPane().add(txtdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 450, 140));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 158, -1));

        addbtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        addbtn.setText("Add");
        addbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 620, 87, -1));

        gbbtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        gbbtn.setText("Go Back");
        gbbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        gbbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gbbtnActionPerformed(evt);
            }
        });
        getContentPane().add(gbbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 77, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Breakfast"},
                {"2", "Lunch"},
                {"3", "Dinner"},
                {"4", "Dessert"},
                {"5", "Drinks"}
            },
            new String [] {
                "NO", "Category"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 280, 130));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Designer.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtdisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdisActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txttilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttilActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
Recipe r= new Recipe();
r.setRecid(txtid.getText());
r.setTitle(txttil.getText());
r.setId((String)cat.getSelectedItem());
r.setPreptime(txtpt.getText());
r.setCtime(txtct.getText());
r.setDisc(txtdis.getText());
Recipedao.save(r);
setVisible(false);
new Newrecip().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_addbtnActionPerformed

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
     validateFields();   // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyReleased

    private void txttilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttilKeyReleased
      validateFields();  // TODO add your handling code here:
    }//GEN-LAST:event_txttilKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<Category> list = Categorydao.getAllRecords();
        Iterator<Category> itr= list.iterator();
        while(itr.hasNext())
        {
            Category categoryobj = itr.next();
            cat.addItem(categoryobj.getId());
        }
    }//GEN-LAST:event_formComponentShown

    private void gbbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gbbtnActionPerformed
setVisible(false);
        new home().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_gbbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newrecip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newrecip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newrecip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newrecip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newrecip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JComboBox<String> cat;
    private javax.swing.JButton gbbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtct;
    private javax.swing.JTextField txtdis;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtpt;
    private javax.swing.JTextField txttil;
    // End of variables declaration//GEN-END:variables
}
